-- MySQL Script generated by MySQL Workbench
-- Sun Jun 13 16:25:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpaceStarships
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpaceStarships
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpaceStarships` DEFAULT CHARACTER SET utf8 ;
USE `SpaceStarships` ;

-- -----------------------------------------------------
-- Table `SpaceStarships`.`TablaResultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpaceStarships`.`TablaResultados` (
  `idScore` INT NOT NULL AUTO_INCREMENT,
  `Fecha` VARCHAR(45) NOT NULL,
  `Score` INT NOT NULL,
  PRIMARY KEY (`idScore`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SpaceStarships`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpaceStarships`.`Equipo` (
  `idEquipo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Muertes` INT NOT NULL,
  `TablaResultados_idScore` INT NOT NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `fk_Equipo_TablaResultados_idx` (`TablaResultados_idScore` ASC) VISIBLE,
  CONSTRAINT `fk_Equipo_TablaResultados`
    FOREIGN KEY (`TablaResultados_idScore`)
    REFERENCES `SpaceStarships`.`TablaResultados` (`idScore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
